version: '3.8'

services:
  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://external-api-url.com/predict  # Replace with your actual URL
